name: Auto Daily Push

on:
  schedule:
    - cron: '38 20 * * *'  # Runs every day at 2:08 AM IST (UTC+5:30)
  workflow_dispatch:        # Allows manual trigger from GitHub Actions tab

permissions:
  contents: write

jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Append to commit log
        run: |
          echo "$(date +'%d-%m-%Y %H:%M:%S IST') - cypress code changes" >> commit-log.txt

      - name: Commit and push
        run: |
          git config user.name "ranajitjyoti"
          git config user.email "ranajitjyoti4@gmail.com"
          git add commit-log.txt
          git commit -m "cypress code changes $(date +'%d-%m-%Y')"
          git push
